install:
# What is it with CMake and not detecting the right versions of libraries...
- del C:\OpenSSL-Win64\lib\ssleay32.lib
- del C:\OpenSSL-Win64\lib\libeay32.lib
- set BOOST_ROOT=C:\Libraries\boost_1_66_0
- set BOOST_LIBRARYDIR=%BOOST_ROOT%\lib64-msvc-14.0

# Setup the submodules from their respective repositories...
- git submodule init
- git submodule update

build_script:
- mkdir build
- cd build
- cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=Release ..
- msbuild /p:Configuration=Release ALL_BUILD.vcxproj
- cd src/Release
- copy /Y C:\OpenSSL-Win64\*eay32.dll .
- 7z a element-win64.zip *
- cd ../../

# Save the build artifacts
artifacts:
- path: build\Release\element-win64.zip
